### ISSUE TITLE
Demos of the component does not actually use component?

### ISSUE THREAD

**Issue by LeaVerou** [yaroluchko/nutrition-facts#1]
The [Demos](https://piazza.com/class/kylm2ly53jy2ea) page does not appear to actually use `<nutrition-facts>` anywhere?

**Comment by yaroluchko** [comment]
I may have misunderstood the assignment, but I thought we had to create the demos before we actually implement the component so I created the demos how I normally would before I package it into a component. The demos are nearly identical to my final component and function the same way so I kept it as is.

I hope that is not a huge issue.

**Comment by LeaVerou** [comment]
The demos are your component in action, so that people viewing them can get a sense of how they can use your component and what it does.

**Comment by yaroluchko** [comment]
I will update the demos to use the nutrition-facts component instead (should still look and work exactly as it does right now). Sorry about that.

**Comment by yaroluchko** [comment]
It wouldn't be too hard of a fix since I do actually have the component.
Should I resubmit it?
